#!/bin/bash

## make a folder `oresult`
folder=oresult
mkdir "$folder"

move_files() { #@ USAGE:
	while read -r file; do
		if [[ "$file" =~ ^.+\.txt$ ]]; then
			if ! [[ "$file" =~ datafiles.txt ]]; then
				mv "$file" "$folder"
			fi
		fi
	done < <(ls)
}

remove_files() { #@ USAGE:
    move_files
	rm -rf "$folder"
}

## list the content of the file
# and move all the text files into the folder
## created above. These files could be deleted.
while getopts ":df" options; do
	case "$options" in
	d)
		echo "-delete by moving the files"
		move_files
		;;
	f)
		echo "-full(y) delete by removing files"
		remove_files
		;;
	*)
		move_files
		;;
	esac
done
# while read -r file; do
# 	if [[ "$file" =~ ^.+\.txt$ ]]; then
# 		if ! [[ "$file" =~ datafiles.txt ]]; then
# 			mv "$file" "$folder"
# 		fi
# 	fi
# done < <(ls)

# if [ -z "$folder" ]; then
# 	echo "No file is clean up"
# else
# 	echo "Delete the files in $folder"
# fi
